{{- if or (eq .Values.installationMode "AP") (eq .Values.installationMode "OES") -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecret}}
  labels:
{{ include "oes.standard-labels" . | indent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end -}}
